//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "noun_roots_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub root: String,
    pub is_regular: bool,
    pub conjugation_group: String,
    pub root_without_accents: String,
    pub exact: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
