//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "noun_conjugation_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub conjugation_group: String,
    pub prefix: Option<String>,
    pub suffix: Option<String>,
    pub morphological_amount: i32,
    pub morphological_case: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
